name: Feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 * * * *

jobs:
  feeds:
    name: Generate Feeds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate DMZJ
      run: |
        mkdir dist
        python rss.py dmzj
    - name: Push changes
      uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          BRANCH: feeds
          FOLDER: dist
          CLEAN: true