name: Feeds

on:
  workflow_dispatch:
  
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**.yml'

  schedule:
    - cron: 0 * * * *

jobs:
  feeds:
    name: Generate Feeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          git clone -b feeds https://github.com/$GITHUB_REPOSITORY dist
      - name: Generate DMZJ
        id: dmzj
        run: python rss.py dmzj || echo "::set-output name=status::failed"
      - name: Generate ACG178
        id: acg178
        run: python rss.py acg178 || echo "::set-output name=status::failed"
      - name: Push RSS
        if: steps.dmzj.outputs.status != 'failed' || steps.acg178.outputs.status != 'failed'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email github-action@users.noreply.github.com
          cd dist && git add . && git commit -am 'Update feeds' && git push https://Apocalypsor:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY || echo 'Updated'
