name: Feeds

on:
  workflow_dispatch:
  
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Feeds.yaml'

  schedule:
    - cron: 0 * * * *

jobs:
  feeds:
    name: Generate Feeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: '0'
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv markdown2
          pipenv install
      - name: Generate DMZJ
        id: dmzj
        run: pipenv run python rss.py dmzj || echo "::set-output name=status::failed"
      - name: Generate ACG178
        id: acg178
        run: pipenv run python rss.py acg178 || echo "::set-output name=status::failed"
      - name: Push RSS
        if: steps.dmzj.outputs.status != 'failed' || steps.acg178.outputs.status != 'failed'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          python -m markdown2 README.md > dist/index.html
          mv dist /tmp
          git config --global user.name "GitHub Action"
          git config --global user.email github-action@users.noreply.github.com
          git checkout --orphan tmp
          rm -rf * && mv /tmp/dist/* . && git add . && git commit -am 'Update feeds'
          git branch -u origin/feeds
          git push -f origin HEAD:feeds || echo 'Updated'
