name: Feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 * * * *

jobs:
  feeds:
    name: Generate Feeds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate
      run: |
        mkdir dist
        python rss.py dmzj
    - uses: autosuite/autocommit@master
      with:
        commit-message: Update Feeds
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        branch: 'feeds'
        directory: 'dist'