name: Feeds

on:
  workflow_dispatch:
  
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**.yml'

  schedule:
    - cron: 0 * * * *

jobs:
  feeds:
    name: Generate Feeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv markdown2
          pipenv install
      - name: Generate DMZJ
        id: dmzj
        run: pipenv run python rss.py dmzj || echo "::set-output name=status::failed"
      - name: Generate ACG178
        id: acg178
        run: pipenv run python rss.py acg178 || echo "::set-output name=status::failed"
      - name: Push RSS
        if: steps.dmzj.outputs.status != 'failed' || steps.acg178.outputs.status != 'failed'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          python -m markdown2 README.md > dist/index.html
          git config --global user.name "GitHub Action"
          git config --global user.email github-action@users.noreply.github.com
          cd dist && git init && git add . && git commit -am 'Update feeds'
          git remote add origin https://${{ github.repository_owner }}:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git push --set-upstream origin feeds
          git push -f || echo 'Updated'
